server:
  port: 8080
spring:
    application:
        name: SpringbootCampusLoveWall
    datasource:
        url: jdbc:mysql://localhost:3306/campus_love_wall?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          initial-size: 5
          max-active: 20

    data:
      redis:
        database: 0
        host: localhost
        port: 6379
        password:
        timeout: 10000
jwt:
  # JWT密钥，生产环境中必须通过环境变量JWT_SECRET配置，不能使用默认值
  secret: ${JWT_SECRET:your-very-secure-secret-key-change-in-production}
  access-token-expire: 3600000        # 1小时毫秒数
  refresh-token-expire: 604800000     # 7天毫秒数
